### ISSUE TITLE
Revive automatic segmentation code

### ISSUE THREAD

**Issue by kwatcharasupat** [FBA-Janitor/MIG-MusicPerformanceAnalysis-Code#2]

**Comment by suncerock** [comment]
The old auto segmentation codes are based on the [dependencies](https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/blob/master/src/auto_segmentation/requirements.txt).

The code works quite well, and the output file looks really as if everything is good, though the results are not evaluated yet.




Model details
- Preprocess: resample to 22kHz, STFT (by scipy, default tukey window), n_fft=4096, hop_lenght=2048
- Feature extraction: calculate features, then combine the smaller frames into larger blocks so that one block records the mean and standard deviation of each small blocks. Each block corresponds to 9 hops, i.e. ~0.836s 
- Feature normalization is missing
- Feed the features into SVM, get 0-1 output
- Postprocess (stage 1) - smooth the output, 0 1 0 -> 0 0 0, 1 0 1 -> 1 1 1 (proposed improvement: add arguments controlling the min length of performance and non-performance)
- If the number of segments (5 exercises per audio) is correct, end. If less than 5 or more than 12, mark it. Otherwise, go to stage 2.
- Stage 2: First throw away all the segments < certain length (~3s), then combine two segments with the shortest non-performance segments between them. Informative post-process requires a higher success rate of stage 1, and I haven't figured out the magic here yet.

I'm planning to re-organize the code a little bit, and make it easier to maintain, and adapt it to new file structure.
- [x] Re-organize the code for inference in scripts
- [x] Evaluate the performance of the model
- [x] (If necessary) Re-organize the code for training in scripts

**Comment by suncerock** [comment]
Old code revived. New code is already in the repo, and the segmentation results is coming soon!
